coverage: 79.7% of statements
two tests are failing and the reason for this is that we are not
handling the command suffix:

=== RUN   TestCmdPrompt
    command_test.go:633: expected output "Z\n", got ""
--- FAIL: TestCmdPrompt (0.00s)

=== RUN   TestCmdLineNumber
=== RUN   TestCmdLineNumber/=_
=== RUN   TestCmdLineNumber/=l_
    command_test.go:1149: expected output "26$\n", got "26\n"
=== RUN   TestCmdLineNumber/=p_
--- FAIL: TestCmdLineNumber (0.00s)
    --- PASS: TestCmdLineNumber/=_ (0.00s)
    --- FAIL: TestCmdLineNumber/=l_ (0.00s)
    --- PASS: TestCmdLineNumber/=p_ (0.00s)